# -*- coding: utf-8 -*-
"""test-conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a974nCKkkQp1bfA5_46OmLigkFsZNyc_

# Convert XML to Pandas DataFrame
- In this notebook, we convert the XML file to a Pandas DataFrame
- Save the DataFrame as a CSV file
- Add new data to the CSV file manully through Excel

## Import Libraries
"""

import xml.etree.ElementTree as ET
import pandas as pd

"""## Load the XML file"""

xmlpath ="/content/drive/MyDrive/Colab Notebooks/Co_op_JohnLiu/data/mitlecture1.xml"

xmlpath ="/content/drive/MyDrive/Colab Notebooks/Co_op_JohnLiu/data/mitlecture2.xml"

xmlpath = "/content/drive/MyDrive/Co_op_JohnLiu/data/mitlecture2.xml"

xmlpath = "/content/drive/MyDrive/Co_op_JohnLiu/data/mitlecture3.xml"



xmlpath_n = "/content/drive/MyDrive/Colab Notebooks/Co_op_JohnLiu/Niyam/Lecture12Transcript.xml"

with open(xmlpath, "r") as f:
    xml_data = f.read()

from google.colab import drive
drive.mount('/content/drive')

xml_data

"""## Parse XML file"""

# Parse XML
root = ET.fromstring(xml_data)

root

# Extract fields for DataFrame
data = []
for segment in root.findall("Lecture_Segment"):
    segment_data = {
        "URL": root.find("URL").text.strip(),
        "Time": segment.get("time"),
        "Transcript_Text": segment.find("Transcript/Text").text.strip(),
        "Transcript_Key_Points": segment.find("Transcript/Key_points").text.strip(),
        "Lecture_Notes_Text": segment.find("Lecture_Notes/Text").text.strip(),
        "Lecture_Notes_Key_Points": segment.find("Lecture_Notes/Key_points").text.strip(),
        "Coverage": segment.find("Coverage").text.strip(),
        "Missing_Points": segment.find("Missing_Points").text.strip()
    }
    data.append(segment_data)

# Create DataFrame
df = pd.DataFrame(data)

df

df.shape

"""## Save to CSV File"""

csvpath ="/content/drive/MyDrive/Co_op_JohnLiu/data/mitlecture3.csv"

df.to_csv(csvpath, index=False)

